spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

   
zuul:
 routes:
   category-biller-info:
      path: /api/biller_cat_microservice/**
      url: http://localhost:8081
#   biller-info:
#      path: /api/biller_microservice/**
#      url: http://localhost:8083